# Generated by Django 4.0.6 on 2022-07-20 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('asset_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('produce', models.CharField(max_length=250)),
                ('weight', models.PositiveIntegerField()),
                ('pick_up_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('ideal_temperature', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
