# Generated by Django 4.0.6 on 2022-07-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturereading',
            old_name='time_id',
            new_name='shipment',
        ),
    ]
