# Generated by Django 4.0.6 on 2022-07-22 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0002_temperature_reading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Container',
            new_name='Shipment',
        ),
        migrations.RenameModel(
            old_name='Temperature_Reading',
            new_name='TemperatureReading',
        ),
    ]
